### ISSUE TITLE
How to run TransformerXL experiment

### ISSUE THREAD

**Issue by alisafaya** [google-research/meliad#3]
Hi, 

Thanks for your work. I would run the Transformer XL model with the medium-150M settings. 
Is removing `recurrent/bias_skip.gin` from the Block Recurrent Transformer settings enough to convert it to TransformerXL or do I need to modify something else?

Edit: I understand that setting segment length and window-size to the same value is required as well for TransformerXL. Where do we set the maximum size of the cache then?

Thanks a lot!

**Comment by delesley** [comment]
You are correct.  If you remove recurrent/bias_skip.gin, then you get Transformer-XL with sliding window attention.

If you further replace options/seq_4096.gin with options/seq_512.gin, then you will get the normal Transformer-XL, without a sliding window.  (The sliding window is enabled automatically if segment length is larger than window length.)  If you use options/seq_512_nocache.gin, then you will get a vanilla transformer, without the Transformer-XL cache.

**Comment by alisafaya** [comment]
Thanks for the quick reply!
